---
- name: Stop SMS Bridge K3s Infrastructure
  hosts: localhost
  become: yes
  
  collections:
    - kubernetes.core

  vars:
    namespace: "sms-bridge"

  tasks:
    - name: Delete SMS Bridge namespace and all resources
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        wait: true
        wait_timeout: 300

    - name: Delete PersistentVolume
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: PersistentVolume
        name: postgres-pv
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Display stop status
      debug:
        msg: "SMS Bridge K3s infrastructure has been stopped and all resources deleted."
