# Example cloudflared config.yml
# Replace example hostnames and service addresses before use

tunnel: <TUNNEL-UUID>
credentials-file: /etc/cloudflared/credentials-file.json

ingress:
  - hostname: sms.example.com
    service: http://host.docker.internal:8080 # Docker desktop host mapping to container host
  - hostname: sms-k3s.example.com
    service: http://sms-receiver.sms-bridge.svc.cluster.local:8080 # K3s internal service
  - service: http_status:404

# Optional: metrics and logging
metrics: 0.0.0.0:8089
loglevel: info

# Notes:
# - Replace <TUNNEL-UUID> with the tunnel UUID created by `cloudflared tunnel create`.
# - `credentials-file.json` must be mounted into the container or available on the host for cloudflared to use.
