# Example cloudflared config.yml
# Replace example hostnames and service addresses before use

tunnel: <TUNNEL-UUID>
credentials-file: /etc/cloudflared/credentials-file.json

ingress:
  # This single rule handles all traffic for the hostname and forwards it to the K3s service.
  # The service itself (sms_server.py) is responsible for routing different paths like /onboard/register and /sms/receive.
  - hostname: sms-k3s.example.com
    service: http://sms-receiver.sms-bridge.svc.cluster.local:8080
  
  # Fallback for any other requests that don't match a hostname
  - service: http_status:404

# Optional: metrics and logging
metrics: 0.0.0.0:8089
loglevel: info

# Notes:
# - Replace <TUNNEL-UUID> with the tunnel UUID created by `cloudflared tunnel create`.
# - `credentials-file.json` must be mounted into the container or available on the host for cloudflared to use.
