version: '3.7'
services:
  cloudflared:
    image: cloudflare/cloudflared:2024.4.0
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: host # uses host networking so host.docker.internal not required on Linux
    volumes:
      - ./credentials-file.json:/etc/cloudflared/credentials-file.json:ro
      - ./config.yml:/etc/cloudflared/config.yml:ro
    command: tunnel run --config /etc/cloudflared/config.yml <TUNNEL-NAME>
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-}
    # If you prefer not to use host networking, remove network_mode and map ports as needed
